org.knime.geo: # {group_id}.{name} from the knime.yml
  src: D:\Software\knime_470\knimespace\geo\geo_extension # Path to folder containing the extension files
  conda_env_path: D:\ProgramData\Anaconda3\envs\my_python_env # Path to the Python environment to use
  debug_mode: true # Optional line, if set to true, it will always use the latest changes of execute/configure, when that method is used within the KNIME Analytics Platform